apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  
type: Opaque
data:
  DB_USER: YWRtaW4=

          # echo -n "admin" | base64
  DB_PASS: QWRtaW4tMTIzNDU=

  # echo -n "yourpassword" | base64
  DB_NAME: c25ha2VfZ2FtZQ==

  # echo -n "snake_game" | base64
